### ISSUE TITLE
Crash on Starmap

### ISSUE THREAD

**Issue by Xilmi** [Zeraan/dg-issue-tracker#13]
ArgumentException: An element with the same key already exists in the dictionary.
System.Collections.Generic.Dictionary`2[StarSystem,Fleet].Add (.StarSystem key, .Fleet value) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:404)
EmpireManager.InnerColonizationCheckLoop (.Fleet fleet) (at Assets/Scripts/EmpireManager.cs:478)
EmpireManager.ResolveColonizationContests () (at Assets/Scripts/EmpireManager.cs:177)
EmpireManager+<ProcessTurnRoutine>c__Iterator6C.MoveNext () (at Assets/Scripts/EmpireManager.cs:118)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
EmpireManager:ProcessTurn() (at Assets/Scripts/EmpireManager.cs:84)
<ComputeNextTurnRoutine>c__Iterator70:MoveNext() (at Assets/Scripts/GameControl.cs:533)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
GameControl:ComputeNextTurn() (at Assets/Scripts/GameControl.cs:521)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by Zeraan** [comment]
This has been basically removed due to new transport mechanisms
